# Scaling Data

Sometimes prior to fitting a model or running an algorithm we will need to scale our data. This is particularly true when some features (columns of $X$) are on vastly different scales than others. In this notebook we will demonstrate how to scale.

## What we will accomplish

In this notebook we will:
- Introduce the concept of scaling your data,
- Demonstrate the `StandardScaler` object in `sklearn`,
- Discuss `fit`, `transform` and `fit_transform` and
- Show the scaling process using `sklearn`.

Before we get started let's generate some data.

In [17]:
import numpy as np
np.random.seed(440)

In [18]:
## Make some data
## Notice that the columns of X have vastly different scales
X = np.zeros((1000,4))
X[:,0] = 1000*np.random.randn(1000)
X[:,1] = np.random.random(1000) - 10
X[:,2] = np.random.randint(-250,150,1000)
X[:,3] = 10*np.random.randn(1000)-75

In [19]:
X

array([[ -320.2545309 ,    -9.3904832 ,   -85.        ,   -89.85286099],
       [ 1090.50674007,    -9.01642287,    60.        ,   -84.00231713],
       [ 1528.86149075,    -9.4104554 ,  -109.        ,   -78.22931661],
       ...,
       [-1334.77532715,    -9.56466439,  -142.        ,   -62.87871873],
       [ -699.54356749,    -9.97809278,    85.        ,   -74.17383445],
       [ 1722.04293527,    -9.12892911,   -94.        ,   -74.72262628]])

In [3]:
## demonstrating the different scales
print("mean of X1:",np.mean(X[:,0]))
print("variance of X1:",np.var(X[:,0]))
print()

print("mean of X2:",np.mean(X[:,1]))
print("variance of X2:",np.var(X[:,1]))
print()

print("mean of X3:",np.mean(X[:,2]))
print("variance of X3:",np.var(X[:,2]))
print()

print("mean of X4:",np.mean(X[:,3]))
print("variance of X4:",np.var(X[:,3]))

mean of X1: 11.935201655200657
variance of X1: 1026903.0991374647

mean of X2: -9.503242684051795
variance of X2: 0.0821580848191559

mean of X3: -52.442
variance of X3: 13772.400636

mean of X4: -74.45477168608731
variance of X4: 96.85199591904106


We can see that the columns of `X` have very different scales. We will soon learn some algorithms whose results can be greatly distorted when this happens.

The main approach to fixing this issue is to scale the data so they are all on the same scale.

## Standardizing your data

While there are a few different ways to scale data, one of the most common is to <i>standardize</i> it. When you standardize a variable, $x$, you apply the following transformation:

$$
x_\text{scaled} = \frac{x - \text{mean}(x)}{\text{standard deviation}(x)},
$$

if you have taken a statistics course (or used $Z$-tables), this should look familiar. This is precisely the transformation applied to turn any arbitary normal random variable into a <i>standard normal</i> random variable, hence the term <i>standardizing</i>.

Standardizing your data will transform it to have mean $0$ and standard deviation $1$.

### `StandardScaler`

We could do this by hand using `numpy`, but that will quickly become tedious. `sklearn` provides a nice `scaler` object called `StandardScaler` that will perform this on all columns of your data set, and has functionality that plays nicely with train test splits. Here is the documentation <a href="https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html">https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html</a>.

In [4]:
## import StandardScaler
from sklearn.preprocessing import StandardScaler

In [10]:
## Make a scaler object
scaler = StandardScaler()

## fit the scaler
scaler.fit(X)

StandardScaler()

In [11]:
scaler.mean_

array([ 11.93520166,  -9.50324268, -52.442     , -74.45477169])

In [7]:
scaler.scale_

array([1.01336227e+03, 2.86632316e-01, 1.17355872e+02, 9.84134116e+00])

In [16]:
X

array([[ -320.2545309 ,    -9.3904832 ,   -85.        ,   -89.85286099],
       [ 1090.50674007,    -9.01642287,    60.        ,   -84.00231713],
       [ 1528.86149075,    -9.4104554 ,  -109.        ,   -78.22931661],
       ...,
       [-1334.77532715,    -9.56466439,  -142.        ,   -62.87871873],
       [ -699.54356749,    -9.97809278,    85.        ,   -74.17383445],
       [ 1722.04293527,    -9.12892911,   -94.        ,   -74.72262628]])

In [13]:
## scale the data, i.e. transform it
X_scale = scaler.transform(X)

In [15]:
scaler.transform(np.array([[1, -2, 81, 9.9999]]))

array([[-1.07910092e-02,  2.61772391e+01,  1.13707135e+00,
         8.58162219e+00]])

In [14]:
## Checking the scaled means and variances
print("mean of standardized X1:",np.mean(X_scale[:,0]))
print("variance of standardized X1:",np.var(X_scale[:,0]))
print()

print("mean of standardized X2:",np.mean(X_scale[:,1]))
print("variance of standardized X2:",np.var(X_scale[:,1]))
print()

print("mean of standardized X3:",np.mean(X_scale[:,2]))
print("variance of standardized X3:",np.var(X_scale[:,2]))
print()

print("mean of standardized X4:",np.mean(X_scale[:,3]))
print("variance of standardized X4:",np.var(X_scale[:,3]))

mean of standardized X1: -2.4868995751603507e-17
variance of standardized X1: 1.000000000000001

mean of standardized X2: -3.849809360190193e-14
variance of standardized X2: 0.9999999999999999

mean of standardized X3: 4.085620730620576e-17
variance of standardized X3: 0.9999999999999991

mean of standardized X4: -1.0054179711005418e-14
variance of standardized X4: 1.0


#### `fit`, `transform` and `fit_transform` & scaling for train test splits

You may be wondering what `fit`, `transform` and `fit_transform` do. Let's describe:
- `fit` performs a fit of the `scaler` object, for `StandardScaler` this means finding the mean and standard deviation of each column and storing it. `fit` must be called <i>before</i> `transform`.
- `transform` is what actually performs the scaling, for `StandardScaler` this means substracting the respective means and dividing by the respective standard deviations for each column. `transform` must be called <i>after</i> `fit`.
- `fit_transform` does this all in one fell swoop, i.e. it fits the `scaler` object then uses the fit to transform the data.

##### Why do we need anything other than `fit_transform`?

Excellent question! In the example above we probably could have just used `fit_transform`.

However, this is because we were not dealing with train test splits, validation sets or cross-validation. We consider scaling the data part of the model, meaning the algorithm/model was fit using the data scaled with the training set's means and standard deviations. For example, if we scaled data prior to fitting a linear regression model, then $\hat{\beta}$ was found using the data scaled according to the training set (using the means and standard deviations of the training set columns). To assess how that particular model performs we must also scale any validation set, cross-validation holdout set or test set using the same exact scaling (i.e. using the means and standard deviations from the training set).

Let's illustrate what I mean with a quick final example.

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test = train_test_split(X,
                                      shuffle=True,
                                      random_state=614,
                                      test_size=.2)

In [22]:
## Fit then transform the training set
scaler_new = StandardScaler()

scaler_new.fit(X_train)

X_train_scale = scaler_new.transform(X_train)

## alternatively I could do
## X_train_scale = scaler_new.fit_transform(X_train), Why?
## because this is the training set, so it is okay to run fit_transform.

<i>Imagine we build a model here.</i>

In [23]:
## Transform the test set
## DO NOT refit the scaler!
X_test_scale = scaler_new.transform(X_test)


<i>Imagine we test model performance on the test set here.</i>

In [24]:
from sklearn.model_selection import KFold

In [25]:
kfold = KFold(5, shuffle=True, random_state = 203)

In [26]:
for train_index, test_index in kfold.split(X_train):
    X_tt = X_train[train_index, :]
    X_ho = X_train[test_index, :]
    
    
    ## make a new scaler here
    scaler_kfold = StandardScaler()
    
    scaler_kfold.fit(X_tt)
    
    print(scaler_kfold.mean_)
    print()
    
    X_tt_scaled = scaler_kfold.transform(X_tt)
    
    X_ho_scaled = scaler_kfold.transform(X_ho)

[ 22.52538957  -9.50562737 -49.0875     -74.45829967]

[ 18.07635978  -9.50923032 -53.121875   -74.44154339]

[ 26.38859272  -9.4999481  -46.5734375  -74.18682472]

[ 50.96297419  -9.49825098 -54.6828125  -74.76305543]

[ 62.77142348  -9.50599823 -53.228125   -74.45668387]



## Other scaler objects

`sklearn` has more scalers than just `StandardScaler`, which you can find at this link, <a href="https://scikit-learn.org/stable/modules/preprocessing.html">https://scikit-learn.org/stable/modules/preprocessing.html</a>. Moreover, some `sklearn` models have their own input arguments that will handle scaling for you when set `= True`.

--------------------------

This notebook was written for the Erd&#337;s Institute C&#337;de Data Science Boot Camp by Matthew Osborne, Ph. D., 2022.

Any potential redistributors must seek and receive permission from Matthew Tyler Osborne, Ph.D. prior to redistribution. Redistribution of the material contained in this repository is conditional on acknowledgement of Matthew Tyler Osborne, Ph.D.'s original authorship and sponsorship of the Erdős Institute as subject to the license (see License.md)