# Shallow and Deep Copies

These problems will cover the concepts touched on in notebook 5. Shallow and Deep Copies

1. Look at the code below, what should happen when it is executed?

When you change the 4th entry of `b` the 4th entry of `a` is also changed, because you only performed a shallow copy.

In [1]:
a = [1,2,3,4,5,6]
b = a
b[3] = 71

print(a)
print(b)

[1, 2, 3, 71, 5, 6]
[1, 2, 3, 71, 5, 6]


2. What would you need to change so that `a` is not changed when you change `b`?

In [2]:
## code or write here
a = [1,2,3,4,5,6]

## put a .copy()
b = a.copy()
b[3] = 71

print(a)
print(b)


[1, 2, 3, 4, 5, 6]
[1, 2, 3, 71, 5, 6]


3. Look at the code below, what should happen when it is executed?

Because you only performed a shallow copy when you change `b` you will also change `a`.

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
b = a

b[2] = 1

print(a)
print(b)

[1 2 1 4]
[1 2 1 4]


4. Perform a web search to find what you would need to change so that `a` is not changed when you change `b`. Write the corrected code below.

In [5]:
## Code here

## it is the same :)
## just add a .copy()

a = np.array([1,2,3,4])
b = a.copy()

b[2] = 1

print(a)
print(b)


[1 2 3 4]
[1 2 1 4]


5. Delete `a` and `b`.

In [6]:
## code here
del a,b



6. In the code below we will create a `pandas` `DataFrame` and store it in the variable `df`. Perform a web search to see how to perform a deep copy of a `DataFrame`. Then make a deep copy of `df` and store it in `df_copy`.

In [7]:
import pandas as pd

df = pd.DataFrame({'column_1':[435, 999, 545],
                      'column_2':["ab", "bc", "de"],
                      'column_3':[True, True, False]})

In [8]:
## code here

## .copy() to the rescue again!
df_copy = df.copy()


--------------------------

This notebook was written for the Erd&#337;s Institute C&#337;de Data Science Boot Camp by Matthew Osborne, Ph. D., 2022.

Any potential redistributors must seek and receive permission from Matthew Tyler Osborne, Ph.D. prior to redistribution. Redistribution of the material contained in this repository is conditional on acknowledgement of Matthew Tyler Osborne, Ph.D.'s original authorship and sponsorship of the Erdős Institute as subject to the license (see License.md)